# Generated by Django 3.1.3 on 2020-11-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio_files'),
        ),
    ]
