# Generated by Django 3.1.3 on 2020-11-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_share', '0002_pack_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='audio_file',
            field=models.FileField(default='', upload_to='audio_files'),
        ),
    ]
