# Generated by Django 3.1.3 on 2020-11-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_share', '0004_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='name',
        ),
        migrations.AddField(
            model_name='pack',
            name='image',
            field=models.ImageField(blank=True, default='pack-default.png', upload_to='pack_pics'),
        ),
    ]
