# Generated by Django 3.1.3 on 2020-11-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound_share', '0005_auto_20201124_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='pack_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sound_share.pack'),
        ),
    ]
