# Generated by Django 3.1.3 on 2020-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_share', '0007_auto_20201124_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='audio_file',
            field=models.FileField(upload_to='audio_files'),
        ),
    ]
