# Generated by Django 3.1.3 on 2020-11-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound_share', '0008_auto_20201124_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='pack_id',
            new_name='pack',
        ),
    ]
