# Generated by Django 3.1.3 on 2020-11-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound_share', '0009_auto_20201124_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sound_share.pack'),
        ),
    ]
