# Generated by Django 3.1.3 on 2020-12-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_share', '0011_sound_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='tempo',
            field=models.IntegerField(null=True),
        ),
    ]
